### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by CHEF-KOCH** [hartwork/klogripper#1]
Is this project still maintained or is there a _better_ solution available?

**Comment by hartwork** [comment]
There is `dmesg --follow` on recent distributions of GNU/Linux by now. Other than that, there are no bug reports for klogripper right now. If there were, I would fix them. Does that answer your question? :)

**Comment by CHEF-KOCH** [comment]
Thank you for the response I was just worried about that it's now 5+ years old and it possible not works anymore. Don't get me wrong we using this on AFWall+ and it works great but in meantime a lot of changed (in ANdroid/Linux). So that's why I've asked that question. 

Again thanks for response, I close it now.

**Comment by hartwork** [comment]
Cool to see klogripper be of use to AFWall+. @CHEF-KOCH , could you
* update the goodpoint-Link in https://github.com/ukanth/afwall/blob/HEAD/external/klogripper/README.md to point to https://github.com/hartwork/klogripper/ and 
* fix the copyright header in https://github.com/ukanth/afwall/blob/HEAD/external/klogripper/main.c to say that it's actually a modification/derivative. Right now it says to be all by me. We can discuss merging changes back if you like (but maybe let's make that a new ticket.)
